apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-restaurant-payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dog-restaurant-payments
  template:
    metadata:
      labels:
        app: dog-restaurant-payments
    spec:
      hostname: dog-restaurant-payments
      serviceAccountName: dog-service-account
      containers:
      - name: dog-restaurant-payments
        image: "${DOG_RESTAURANT_PAYMENTS_IMAGE}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "us-east-1"   
#        - name: DB_NAME
#          value: "${DB_NAME}"
#        - name: DB_PORT
#          value: "${DB_PORT}"    
#        - name: DB_USER
#          value: "${DB_USER}"     
#        - name: DB_PASSWORD
#          value: "${DB_PASSWORD}"
#        - name: DB_HOST
#          value: "${DB_HOST}"