apiVersion: v1
kind: Service
metadata:
  name: dog-restaurant-payments
spec:
  selector:
    app: dog-restaurant-payments
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP